### ISSUE TITLE
Is it possible to pull in AmmoJS?

### ISSUE THREAD

**Issue by thewebadmin** [JohnnyDevNull/ng-three-template#10]
I love your template project, has definitely helped me start learning how to build things in ThreeJS but I am now at the point that I want some objects to be able to be thrown and rolled around. Would you be able to update your project with AmmoJS in it? So far I have been very unsuccessful in getting the package to load, constantly getting the error: `Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat ‘C:\hiberfil.sys‘`. Any help would be greatly appreciated!

**Comment by JohnnyDevNull** [comment]
Hi @thewebadmin, well this template is designed to be as simple as possible with only the dependencies in it which would be minimum necessary to start Angular together with ThreeJS, so sadly to say i would not like to include AmmoJS here, because it's a project specific dependency.

If you need any integration help i can recommend you the official ThreeJS community https://discourse.threejs.org/
By the way, there you can find Developers which are much more experienced than me with ThreeJS.
